////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////  THIS FILE WAS AUTO-GENERATED - DO NOT EDIT  ///////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef PLUGINS_CONFIG_H_
#define PLUGINS_CONFIG_H_

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
// CONFIGURATION MACROS
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

#define __PLUGIN_LOW_POWER_ACTOR_X_POSITION (-184)
#define __PLUGIN_LOW_POWER_ACTOR_Y_POSITION (108)
#define __PLUGIN_LOW_POWER_ACTOR_Z_POSITION (0)

#define __PLUGIN_AUTOMATIC_PAUSE_TITLE_TEXT_FONT "AstonishExt"
#define __PLUGIN_AUTOMATIC_PAUSE_BODY_TEXT_FONT "DefaultExt"
#define __PLUGIN_AUTOMATIC_PAUSE_USE_LOW_POWER_ACTOR (1)
#define __PLUGIN_AUTOMATIC_PAUSE_DELAY (30)

#define __PLUGIN_LOW_POWER_INDICATOR_FLASH_DELAY (2)
#define __PLUGIN_LOW_POWER_INDICATOR_FONT "Default"
#define __PLUGIN_LOW_POWER_INDICATOR_ON_TEXT "\x01\x02"
#define __PLUGIN_LOW_POWER_INDICATOR_OFF_TEXT "  "
#define __PLUGIN_LOW_POWER_INDICATOR_X_POSITION (1)
#define __PLUGIN_LOW_POWER_INDICATOR_Y_POSITION (1)

#define __PLUGIN_SAVE_DATA_MANAGER_CRC_MASK (0xEDB88320)
#define __PLUGIN_SAVE_DATA_MANAGER_CRC_CHECK_RANGE (512)
#define __PLUGIN_SAVE_DATA_MANAGER_SAVE_STAMP "VUEngineShowcase"
#define __PLUGIN_SAVE_DATA_MANAGER_SAVE_STAMP_LENGTH (16)

#define __PLUGIN_DWARF_PLANET_STARTING_ROW (82)
#define __PLUGIN_DWARF_PLANET_ENDING_ROW (224)
#define __PLUGIN_DWARF_PLANET_STARTING_COLUMN (22)
#define __PLUGIN_DWARF_PLANET_ENDING_COLUMN (362)

#define __PLUGIN_RAIN_X_POSITION (768)
#define __PLUGIN_RAIN_Y_POSITION (576)
#define __PLUGIN_RAIN_WIDTH (336)
#define __PLUGIN_RAIN_HEIGHT (112)
#define __PLUGIN_RAIN_Y_STEP_THROTTLE (0)

#define __PLUGIN_TILT_STARTING_ROW (82)
#define __PLUGIN_TILT_ENDING_ROW (224)

#define __PLUGIN_WOBBLE_STARTING_ROW (82)
#define __PLUGIN_WOBBLE_ENDING_ROW (220)

#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_USE_LOW_POWER_ACTOR (1)
#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_LOW_POWER_INDICATOR_X_POSITION (4)
#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_LOW_POWER_INDICATOR_Y_POSITION (1)
#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_LOW_POWER_ACTOR_X_POSITION (-152)
#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_LOW_POWER_ACTOR_Y_POSITION (-100)
#define __PLUGIN_ADJUSTMENT_SCREEN_VUENGINE_LOW_POWER_ACTOR_Z_POSITION (0)

#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_USE_LOW_POWER_ACTOR (1)
#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_OPTIONS_GAP (3)
#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_OPTIONS_Y_POS (15)
#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_TITLE_TEXT_FONT "AstonishExt"
#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_BODY_TEXT_FONT "DefaultExt"
#define __PLUGIN_AUTOMATIC_PAUSE_SELECTION_SCREEN_OPTIONS_TEXT_FONT "DefaultExt"

#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_USE_LOW_POWER_ACTOR (1)
#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_VARIANT (1)
#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_TITLE_TEXT_FONT "AstonishExt"
#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_LANGUAGE_NAME_FONT "DefaultExt"
#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_IMAGE_WIDTH (44)
#define __PLUGIN_LANGUAGE_SELECTION_SCREEN_IMAGE_HEIGHT (32)

#define __PLUGIN_PRECAUTION_SCREEN_USE_LOW_POWER_ACTOR (1)
#define __PLUGIN_PRECAUTION_SCREEN_TEXT_FONT "AstonishExt"

#endif
