#include <MIDI.h>

#define EXPLOSION_FREQ    	0x3E8
#define EXPLOSION_DURATION 	500


const uint16 ExplosionSoundTrack[] =
{	
	EXPLOSION_FREQ, EXPLOSION_FREQ, EXPLOSION_FREQ, EXPLOSION_FREQ, EXPLOSION_FREQ, ENDSOUND,
	EXPLOSION_DURATION, EXPLOSION_DURATION, EXPLOSION_DURATION, EXPLOSION_DURATION, EXPLOSION_DURATION, 
	14, 12, 10, 8, 4,
	1, 1, 1, 1, 1
};
