#include <MIDI.h>

#define KILLED_FREQ    	0x3E8
#define KILLED_DURATION 	100


const uint16 KilledSoundTrack[] =
{	
	KILLED_FREQ, KILLED_FREQ, KILLED_FREQ, ENDSOUND,
	KILLED_DURATION, KILLED_DURATION, KILLED_DURATION, 
	10, 8, 4,
	3, 3, 3
};
