#include <MIDI.h>

#define ENGINE__FREQ    		0x8FF
#define ENGINE__DURATION 		80
#define ENGINE__VOLUME_DELTA 	0

const uint16 EngineSoundTrack[] =
{
  HOLD, 0x016 + ENGINE__FREQ, 0x016 + ENGINE__FREQ, 0x016 + ENGINE__FREQ, 0x024 + ENGINE__FREQ, 0x024 + ENGINE__FREQ, 0x032 + ENGINE__FREQ, 0x032 + ENGINE__FREQ, 0x040 + ENGINE__FREQ, 0x032 + ENGINE__FREQ, 0x032 + ENGINE__FREQ, 0x024 + ENGINE__FREQ, 0x024 + ENGINE__FREQ, 0x016 + ENGINE__FREQ, 0x016 + ENGINE__FREQ, 0x016 + ENGINE__FREQ, ENDSOUND,
  1, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION, ENGINE__DURATION,
  14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 15 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 14 + ENGINE__VOLUME_DELTA, 
};
